# Stack file for the Conjure program generation library.
#
# Copyright (C) 2021-2025 Rudy Matela
# Distributed under the 3-Clause BSD licence (see the file LICENSE).

resolver: lts-21.25 # or ghc-9.4.8

packages:
- .

extra-deps:
- leancheck-1.0.2
- speculate-0.4.20
- express-1.0.16
