#!/bin/bash

run1() {
	echo -n "$@" ""
	/usr/bin/time -f%e "$@" 2>&1 >/dev/null
}

run6() {
	run1 "$@"
	run1 "$@"
	run1 "$@"
	run1 "$@"
	run1 "$@"
	run1 "$@"
}

avgs() {
runhaskell <<HASKELL
import Data.List
import Data.Function
import Text.Printf

groupOn f  =  groupBy ((==) \`on\` f)

parseLine :: String -> (String,Double)
parseLine s  =  (n,t)
  where
  n  =  unwords $ init ws
  t  =  read $ last ws
  ws  =  words s

showLine :: (String,Double) -> String
showLine (s,x)  =  printf "%-25s %.2f" s x

collapseAvg :: [(String,Double)] -> (String,Double)
collapseAvg sxs  =  (fst $ head sxs, avg $ map snd sxs)

avg :: [Double] -> Double
avg xs  =  sum xs / fromIntegral (length xs)

io :: String -> String
io  =  unlines
    .  map showLine
    .  map collapseAvg
    .  groupOn fst
    .  map parseLine
    .  lines

main :: IO ()
main  =  interact io
HASKELL
}

tmpfile=`mktemp /tmp/conjure-bench-XXXXXXXXXX`
for fun in factorial sum product length
do
	run6 $1 "$fun"
	run6 $1 "$fun" t
done | tee $tmpfile
avgs <$tmpfile
rm $tmpfile
